// components/RepoCard.vue
<script lang="ts" setup>
const props = defineProps<{
  repo: string;
  title?: string;
  image?: string;
}>();

const appConfig = useAppConfig();

const owner = computed(() =>
  props.repo.includes("/")
    ? props.repo.split("/", 1)[0]
    : appConfig.socials.github,
);
const name = computed(() =>
  props.repo.includes("/") ? props.repo.split("/", 2)[1] : props.repo,
);

const { data } = await useFetch(`/api/repos/${owner.value}/${name.value}`, {
  key: `gh-${owner.value}-${name.value}`,
});

const image = computed(() => {
  if (props.image?.startsWith("http")) {
    return props.image;
  }
  if (props.image?.startsWith("/")) {
    return props.image;
  }
  if (props.image) {
    return `https://raw.githubusercontent.com/${owner.value}/${name.value}/main/${props.image}`;
  }
  if (data.value?.image?.startsWith("https://opengraph.githubassets.com")) {
    return undefined;
  }
  if (data.value?.image) {
    return data.value.image;
  }
});

const hasEmoji = computed(() => data.value && /^\W/.test(data.value.title));
</script>

<template>
  <div
    v-if="data"
    class="max-w-96 min-w-82 flex flex-col b rd-md shadow-lg transition-transform hover:scale-102"
    :class="{
      'b-green-5/50 bg-green-5/10': data.new,
      'bg-neutral-800/60': !data.new,
    }"
  >
    <div class="flex items-center justify-between p-4">
      <div class="flex flex-col">
        <div class="flex items-center gap-2 text-lg font-bold">
          <div
            v-if="data.icon && !hasEmoji"
            :class="data.icon"
            class="shrink-0 text-24px"
          />
          {{ title || data.title }}
        </div>

        <NuxtLink
          :to="`https://github.com/${owner}/${name}`"
          class="mt-1 text-sm text-blue-600 font-medium leading-tight dark:text-blue-500"
        >
          {{ owner }}/{{ name }}
        </NuxtLink>
      </div>

      <NuxtLink
        v-if="data.homepage"
        :to="data.homepage"
        class="i-octicon-home-16 ml-6 mr-2.5 shrink-0 text-20px decoration-none icon-btn"
      />
    </div>

    <div grow b-t p-4 text-sm>
      {{ data.description }}
    </div>

    <div v-if="image">
      <NuxtImg
        :src="image"
        height="192"
        width="382"
        fit="outside"
        loading="lazy"
        class="mx-auto h-192px b-t"
        placeholder
      />
    </div>

    <div
      class="flex b-t text-sm divide-x"
      un-children="flex items-center p-2 basis-1/3 grow justify-center"
    >
      <div>
        <LangDot :color="data.language" />
        <span class="capitalize">{{ data.language }}</span>
      </div>
      <NuxtLink
        v-if="data.license"
        :to="`https://github.com/${owner}/${name}/blob/${data.branch}/LICENSE`"
        decoration-none
      >
        <div i-octicon-law-16 mr-2 text-21px text-zinc-400 />
        <span>{{ data.license }}</span>
      </NuxtLink>
      <NuxtLink
        v-if="data.stars"
        :to="`https://github.com/${owner}/${name}/stargazers`"
      >
        <div i-octicon-star-16 mr-2 text-21px text-zinc-400 />
        <span>{{ data.stars }}</span>
      </NuxtLink>
    </div>
  </div>
</template>

// src/components/RepoCard.tsx
import { Link } from "@tanstack/react-router";
import { cn } from "@/lib/utils.ts";
import type { getRepoData } from "@/utils/getRepoData.ts";
import { LangDot } from "./LangDot.tsx";

type RepoCardProps = Awaited<ReturnType<typeof getRepoData>>;

export const RepoCard = ({
  repo,
  title,
  image,
  icon,
  homepage,
  description,
  language,
  license,
  branch = "main",
  stars,
  ...props
}: RepoCardProps) => {
  const imageUrl = useMemo(() => {
    if (image?.startsWith("https://opengraph.githubassets.com"))
      return undefined;
    if (image?.startsWith("http")) return image;
    if (image?.startsWith("/")) return image;
    if (image) return `https://raw.githubusercontent.com/${repo}/main/${image}`;
    return "";
  }, [image, repo]);

  const hasEmoji = useMemo(() => title && /^\W/.test(title), [title]);
  const repoUrl = `https://github.com/${repo}`;

  return (
    <div
      className={cn(
        "flex min-w-82 max-w-96 flex-col rounded-md border border-[#525252] shadow-lg transition-transform hover:scale-102",
        props.new ? "border-green-500/50 bg-green-500/10" : "bg-neutral-800/60",
      )}
    >
      <div className="flex items-center justify-between p-4">
        <div className="flex flex-col">
          <div className="flex items-center gap-2 font-bold text-lg">
            {icon && !hasEmoji && (
              <i className={cn(icon, "shrink-0 text-[24px]")} aria-hidden />
            )}
            {title}
          </div>

          <Link
            to={repoUrl}
            className="mt-1 font-medium text-blue-600 text-sm leading-tight dark:text-blue-500"
          >
            {repo}
          </Link>
        </div>

        {homepage ? (
          <a
            href={homepage}
            className="i-[octicon--home-16] icon-btn mr-2.5 ml-6 shrink-0 text-[20px] no-underline"
          />
        ) : null}
      </div>

      <div className="grow border-[#525252] border-t p-4 text-sm">
        {description}
      </div>

      {imageUrl ? (
        <div>
          <img
            src={imageUrl}
            alt={title}
            loading="lazy"
            className="mx-auto h-48 w-95.5 border-[#525252] border-t object-contain"
          />
        </div>
      ) : null}

      <div
        className={cn(
          "flex divide-x divide-[#525252] border-[#525252] border-t text-sm",
          "*:flex *:grow *:basis-1/3 *:items-center *:justify-center *:p-2",
        )}
      >
        <div>
          <LangDot color={language} />
          <span className="capitalize">{language}</span>
        </div>

        {license ? (
          <a
            href={`${repoUrl}/blob/${branch}/LICENSE`}
            className="no-underline"
          >
            <i className="i-[octicon--law-16] mr-2 text-[21px] text-zinc-400" />
            <span>{license}</span>
          </a>
        ) : null}

        {stars ? (
          <a href={`${repoUrl}/stargazers`} className="no-underline">
            <i className="i-[octicon--star-16] mr-2 text-[21px] text-zinc-400" />
            <span>{stars}</span>
          </a>
        ) : null}
      </div>
    </div>
  );
};
